#! /bin/bash

sudo apt install apt install libxrender1

wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

tar xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
rm -f /usr/local/bin/wkht*
rm -f /usr/bin/wkht*
cp -r wkhtmltox/bin/* /usr/local/bin/
cp -r wkhtmltox/bin/* /usr/bin/
